language: node_js
node_js:
  - "12.19.0"
script:
  - npm run build
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "github@greggman.com"

deploy:
  provider: pages:git
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  edge: true # opt in to dpl v2
  skip-cleanup: true
  keep-history: true
  local-dir: build
  # ⋮
  on:
    repo: greggman/jsgist
    branch: main
